import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopBar from "../../components/TopBar";
import SideBar from "../../components/SideBar";
import SportsBar from "../../components/SportsBar";
import HomeBar from "../../components/HomeBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Welcome to 99exch",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen flex flex-col`}
      >
        <TopBar />
        <HomeBar />
        <div className="flex flex-1">
          <SideBar />
          <div className="flex-4 bg-gray-200 h-full">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
